/* @flow */
export const UPDATE_FIELD = 'UPDATE_FIELD'
export const UPDATE_ALL = 'UPDATE_ALL'
export const VALIDATE_FIELD = 'VALIDATE_FIELD'
export const VALIDATE_ALL = 'VALIDATE_ALL'
export const VALIDATE_FIELD_SYNC = 'VALIDATE_FIELD_SYNC'
export const VALIDATE_FIELD_ASYNC = 'VALIDATE_FIELD_ASYNC'
export const VALIDATE_ALL_SYNC = 'VALIDATE_ALL_SYNC'
export const VALIDATE_ALL_ASYNC = 'VALIDATE_ALL_ASYNC'
