/* @flow */
export const UPDATE_FIELD = 'UPDATE_FIELD'
export const UPDATE_ALL = 'UPDATE_ALL'
export const VALIDATE_ALL = 'VALIDATE_ALL'
export const VALIDATE_FIELD = 'VALIDATE_FIELD'
export const UPDATE_FIELD_ONLY = 'UPDATE_FIELD_ONLY'
export const VALIDATE_FIELD_ONLY = 'VALIDATE_FIELD_ONLY'
